/*var big = document.querySelector('.big-product')
var one = document.querySelector('.one')
var two = document.querySelector('.two')
var three = document.querySelector('.three')
var four = document.querySelector('.four')
var five = document.querySelector('.five')
var five1 = document.querySelector('.five-one')
var five2 = document.querySelector('.five-two')
var five3 = document.querySelector('.five-three')
var six = document.querySelector('.six')
var seven = document.querySelector('.seven')
var blusher = document.querySelector('.blusher')
var eyeb = document.querySelector('.eyebrows')
var facial = document.querySelector('.facial')
var tint = document.querySelector('.tint')
var stick1 = document.querySelector('.stick-one')
var stick2 = document.querySelector('.stick-two')
var stick3 = document.querySelector('.stick-three')
var eyes = document.querySelector('.eyeshadow')
var keep = document.querySelector('.keep-in-touch')
var hide = document.querySelector('.hide')
one.addEventListener('click', function () {
    eyeb.classList.add('hide')
    facial.classList.add('hide')
    tint.classList.add('hide')
    stick1.classList.add('hide')
    stick2.classList.add('hide')
    stick3.classList.add('hide')
    eyes.classList.add('hide')
    keep.classList.add('hide')
    blusher.classList.remove('hide')
})
two.addEventListener('click', function () {
    eyeb.classList.remove('hide')
    facial.classList.add('hide')
    tint.classList.add('hide')
    stick1.classList.add('hide')
    stick2.classList.add('hide')
    stick3.classList.add('hide')
    eyes.classList.add('hide')
    keep.classList.add('hide')
    blusher.classList.add('hide')
})
three.addEventListener('click', function () {
    eyeb.classList.add('hide')
    facial.classList.remove('hide')
    tint.classList.add('hide')
    stick1.classList.add('hide')
    stick2.classList.add('hide')
    stick3.classList.add('hide')
    eyes.classList.add('hide')
    keep.classList.add('hide')
    blusher.classList.add('hide')
})
four.addEventListener('click', function () {
    eyeb.classList.add('hide')
    facial.classList.add('hide')
    tint.classList.remove('hide')
    stick1.classList.add('hide')
    stick2.classList.add('hide')
    stick3.classList.add('hide')
    eyes.classList.add('hide')
    keep.classList.add('hide')
    blusher.classList.add('hide')
})
five.addEventListener('click', function () {
    eyeb.classList.add('hide')
    facial.classList.add('hide')
    tint.classList.add('hide')
    stick1.classList.remove('hide')
    stick2.classList.remove('hide')
    stick3.classList.remove('hide')
    eyes.classList.add('hide')
    keep.classList.add('hide')
    blusher.classList.add('hide')
})
five1.addEventListener('click', function () {
    eyeb.classList.add('hide')
    facial.classList.add('hide')
    tint.classList.add('hide')
    stick1.classList.remove('hide')
    stick2.classList.add('hide')
    stick3.classList.add('hide')
    eyes.classList.add('hide')
    keep.classList.add('hide')
    blusher.classList.add('hide')
})
five2.addEventListener('click', function () {
    eyeb.classList.add('hide')
    facial.classList.add('hide')
    tint.classList.add('hide')
    stick1.classList.add('hide')
    stick2.classList.remove('hide')
    stick3.classList.add('hide')
    eyes.classList.add('hide')
    keep.classList.add('hide')
    blusher.classList.add('hide')
})
five3.addEventListener('click', function () {
    eyeb.classList.add('hide')
    facial.classList.add('hide')
    tint.classList.add('hide')
    stick1.classList.add('hide')
    stick2.classList.add('hide')
    stick3.classList.remove('hide')
    eyes.classList.add('hide')
    keep.classList.add('hide')
    blusher.classList.add('hide')
})
six.addEventListener('click', function () {
    eyeb.classList.add('hide')
    facial.classList.add('hide')
    tint.classList.add('hide')
    stick1.classList.add('hide')
    stick2.classList.add('hide')
    stick3.classList.add('hide')
    eyes.classList.remove('hide')
    keep.classList.add('hide')
    blusher.classList.add('hide')
})
seven.addEventListener('click',function(){
    eyeb.classList.add('hide')
    facial.classList.add('hide')
    tint.classList.add('hide')
    stick1.classList.add('hide')
    stick2.classList.add('hide')
    stick3.classList.add('hide')
    eyes.classList.add('hide')
    keep.classList.remove('hide')
    blusher.classList.add('hide')
})
*/
/* Dark-light mode */
const body=document.querySelector('body');
const toggle=document.getElementById('toggle');
toggle.onclick =function(){
    toggle.classList.toggle('light');
    body.classList.toggle('light');
}

var read = document.querySelector('.read');
var hide = document.querySelector('.hide');
    read.addEventListener('click' , function(){
        hide.classList.remove('hide');
    })
